Fix build on FreeBSD 8 and earlier.
FreeBSD before version 9 uses struct utmp, which does not contain ut_pid.

cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_BSD=1 -DPSUTIL_VERSION=540 -DPSUTIL_FREEBSD=1 -I/usr/local/include/python2.7 -c psutil/_psutil_bsd.c -o build/temp.freebsd-8.4-RELEASE-amd64-2.7/psutil/_psutil_bsd.o
psutil/_psutil_bsd.c: In function 'psutil_users':
psutil/_psutil_bsd.c:832: error: 'struct utmp' has no member named 'ut_pid'
error: command 'cc' failed with exit status 1
*** Error code 1